# NumPy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,6,8,2,1,6])
b = np.array([[1,2.5,6],[3,4,6]])
print(f'''
Array a: {a} 

Array b: \n
{b}

Dimension a: {a.ndim}

Dimension b: {b.ndim}

Type a: {a.dtype}

Type b: {b.dtype}

Shape a: {a.shape}

Shape b: {b.shape}
''')

### *we can also change the dtype of the array*

In [ ]:
c = np.array([1,9,2,], dtype='int16')
print(c.dtype)

### *Accessing/changing specific columns, rows, elements*

In [65]:
Array_1 = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

print(Array_1[0, :])
print(Array_1[0][1:5])
print(Array_1[0, 1:5])
print(Array_1[1, 1:5])
Array_1.dtype='int32'

print(Array_1)


[1 2 3 4 5 6 7]
[2 3 4 5]
[2 3 4 5]
[ 9 10 11 12]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


#### *changing the values*

In [81]:
Array_1[1,5] = 20
Array_1[0,6] = 10
print(Array_1)


[[ 1  2  3  4  5  6 10]
 [ 8  9 10 11 12 20 14]]


In [87]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [2]:
pip install bs4

In [9]:
import requests
from bs4 import BeautifulSoup

profile_urls = []  # To store the Profile URLs
ctr = 0  # To traverse through Google results pages

while ctr < 15000:
    query = ('https://www.google.com/search?q=site:linkedin.com/in '
             'AND "Data Science"&start=') + str(ctr)
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    
    response = requests.get(query, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')
    
    for anchor in soup.find_all('a'):
        if 'href' in anchor.attrs:  # Check if 'href' attribute exists
            url = anchor['href']
            if 'https://www.linkedin.com/' in url:
                start = url.find('https://www.linkedin.com/')
                end = url.find('&', start)
                if end == -1:
                    end = None
                profile_url = url[start:end]
                profile_urls.append(profile_url)
                print(profile_url)
    
    ctr += 10


KeyboardInterrupt: 

In [11]:
a = 0
for i in range(5):
    a = a + i
    if i == 3:
        break
print(a)

6
